version: '3.8'

services:
  backend:
    build: . # Uses the single Dockerfile in the current directory
    container_name: flask-backend
    command: gunicorn --bind 0.0.0.0:3000 wsgi:web_app # Run Gunicorn
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

  worker:
    build: . # Uses the *same* single Dockerfile
    container_name: celery-worker
    command: celery -A app.celery worker -l info # Run Celery worker
    depends_on:
      - backend # Depend on web to ensure common setup runs first, if needed
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    command: npm run dev -- --host

  flower:
    build: .
    container_name: celery-flower
    command: celery -A app.celery flower
    ports:
      - "5555:5555"
    depends_on:
      - worker
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge